version: "3.2"
services:

  statistics:
    image: bgornicki/engrave-statistics
    depends_on:
      - mongo
    environment:
      - WAIT_HOSTS=mongo:27017  
  
  nginx:
    image: bgornicki/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/letsencrypt
    depends_on:
      - engrave

  engrave:
    image: bgornicki/engrave
    environment:
      - DOMAIN=engrave.website
      - SSL_EMAIL=engrave@niepodam.pl
      - SSL_CERTIFICATES_DIR=/etc/letsencrypt
      - BLOGS_DOMAINS=["engrave.website", "engrave.site"]
      - BLOGS_CATEGORIES=["Other", "Financial and economy", "Lifestyle", "Food", "Sport", "Travel", "Health and beauty", "Hobby", "Music", "Journalism", "Photography", "Technology"]
      - WAIT_HOSTS=mongo:27017
      - SERVER_IP=139.162.185.235
      - PAYMENT_REDIRECT_URI=https://engrave.website/dashboard/configure/
      - NAMECOM_API=api.name.com
      - DOMAIN_PRICE_SBD=15
      - DOMAIN_PRICE_STEEM=35
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/letsencrypt
    depends_on:
      - mongo
    secrets:
      - NAMECOM_TOKEN
      - NAMECOM_USERNAME

  mongo:
    image: mongo
    volumes:
      - db-data:/data/db

volumes:
  db-data:
  nginx_certs:
  nginx_conf:

secrets:
  NAMECOM_TOKEN:
    external: true
  NAMECOM_USERNAME:
    external: true