version: "3.2"
services:

  api-gateway:
    image: bgornicki/engrave-api-gateway
    
  statistics:
    image: bgornicki/engrave-statistics
    depends_on:
      - mongo
    environment:
      - WAIT_HOSTS=mongo:27017  

  image-uploader:
    image: bgornicki/engrave-image-uploader
    secrets:
      - IMGUR_KEY
      - IMGUR_CLIENT_ID
  
  nginx:
    image: bgornicki/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/letsencrypt
    depends_on:
      - engrave

  engrave:
    image: bgornicki/engrave
    environment:
      - DOMAIN=dblog.pl
      - SSL_EMAIL=engrave@niepodam.pl
      - SSL_CERTIFICATES_DIR=/etc/letsencrypt
      - BLOGS_DOMAINS=["dblog.pl"]
      - BLOGS_CATEGORIES=["Inne", "Finanse i ekonomia", "Lifestyle", "Jedzenie", "Sport", "Podróże", "Zdrowie i uroda", "Hobby", "Muzyka", "Dziennikarstwo", "Fotografia", "Technologia"]
      - WAIT_HOSTS=mongo:27017
      - SERVER_IP=172.104.225.127
      - PAYMENT_REDIRECT_URI=https://dblog.pl/dashboard/configure/
      - NAMECOM_API=api.name.com
      - DOMAIN_PRICE_SBD=15
      - DOMAIN_PRICE_STEEM=35
      - FRONT=dblog
      - STEEMCONNECT_ID=dblog.app
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/letsencrypt
    depends_on:
      - mongo
    secrets:
      - NAMECOM_TOKEN
      - NAMECOM_USERNAME

  mongo:
    image: mongo
    volumes:
      - db-data:/data/db

volumes:
  db-data:
  nginx_certs:
  nginx_conf:

secrets:
  NAMECOM_TOKEN:
    external: true
  NAMECOM_USERNAME:
    external: true
  IMGUR_KEY:
    external: true
  IMGUR_CLIENT_ID:
    external: true