version: "3.2"
services:

  api-gateway:
    image: bgornicki/engrave-api-gateway
    ports:
      - 3002:3000
      - 3003:3001

  statistics:
    image: bgornicki/engrave-statistics
    depends_on:
      - mongo
    environment:
      - WAIT_HOSTS=mongo:27017

  image-uploader:
    image: bgornicki/engrave-image-uploader
    ports:
      - 3000:3000
      - 3001:3001
    secrets:
      - IMGUR_KEY
      - IMGUR_CLIENT_ID
    volumes:
      - ./engrave-image-uploader/src:/app/src
      - ./engrave-image-uploader/dist:/app/dist
  
  nginx:
    image: bgornicki/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/letsencrypt
    depends_on:
      - engrave

  engrave:
    image: bgornicki/engrave
    ports:
      - 9229:9229
    environment:
      - STEEMCONNECT_REDIRECT_URI=http://127.0.0.1/authorize/
      - PAYMENT_REDIRECT_URI=http://127.0.0.1/dashboard/configure/
      - DOMAIN=engrave.website
      - SSL_EMAIL=engrave@niepodam.pl
      - SSL_CERTIFICATES_DIR=/etc/letsencrypt
      - BLOGS_DOMAINS=["engrave.website", "engrave.site"]
      - BLOGS_CATEGORIES=["Other", "Financial and economy", "Lifestyle", "Food", "Sport", "Travel", "Health and beauty", "Hobby", "Music", "Journalism", "Photography", "Technology"]
      - WAIT_HOSTS=mongo:27017
      - SERVER_IP=139.162.185.235
      - NAMECOM_API=api.dev.name.com
      - DOMAIN_PRICE_SBD=10
      - DOMAIN_PRICE_STEEM=20
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/letsencrypt
      - ./engrave/src:/app/src
      - ./engrave/views:/app/views
      - ./engrave/public:/app/public
      - ./engrave/dist:/app/dist
    depends_on:
      - mongo
    secrets:
      - NAMECOM_TOKEN
      - NAMECOM_USERNAME
      
  mongo:
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
    - "27017:27017"


volumes:
  db-data:
  nginx_certs:
  nginx_conf:
 
secrets:
  NAMECOM_TOKEN:
    external: true
  NAMECOM_USERNAME:
    external: true
  IMGUR_KEY:
    external: true
  IMGUR_CLIENT_ID:
    external: true